In [1]:
# Import the library

import pandas as pd
import numpy as np

In [2]:
# Read the file

bcc = pd.read_csv(r"C:\Users\Fahim\Desktop\NAIM\pranjal\BankCreditCard.csv")

In [3]:
# Check the first 5 records 

bcc.head()


Customer ID  Credit_Amount  Gender  Academic_Qualification  Marital  \
0            1        20000.0       2                       2        1   
1            2       220000.0       2                       2        2   
2            3        90000.0       2                       2        2   
3            4        50000.0       2                       2        1   
4            5        50000.0       1                       2        1   

   Age_Years  Repayment_Status_Jan  Repayment_Status_Feb  \
0         24                     2                     2   
1         26                     0                     2   
2         34                     0                     0   
3         37                     0                     0   
4         57                     0                     0   

   Repayment_Status_March  Repayment_Status_April  ...  April_Bill_Amount  \
0                       0                       0  ...                0.0   
1                       0                       0  ...             3272.0   
2                       0                       0  ...            24332.0   
3                       0                       0  ...            29324.0   
4                       0                       0  ...            20940.0   

   May_Bill_Amount  June_Bill_Amount  Previous_Payment_Jan  \
0              0.0               0.0                   0.0   
1           3455.0            3261.0                   0.0   
2          14848.0           15548.0                1619.0   
3          28858.0           28547.0                3000.0   
4          18146.0           18131.0                3000.0   

   Previous_Payment_Feb  Previous_Payment_March  Previous_Payment_April  \
0                 679.0                     0.0                     0.0   
1                2000.0                  1000.0                  1000.0   
2                2500.0                  1000.0                  1000.0   
3                2029.0                  1200.0                  1100.0   
4               36672.0                 10000.0                  9000.0   

   Previous_Payment_May  Previous_Payment_June  Default_Payment  
0                   0.0                    0.0                1  
1                   0.0                 2000.0                1  
2                1000.0                 5000.0                0  
3                1069.0                 1000.0                0  
4                 689.0                  679.0                0  

[5 rows x 25 columns]

In [4]:
# Check the shape. 
bcc.shape

(30000, 25)

In [5]:
# Check if any nulls 
bcc.isnull().sum()

Customer ID               0
Credit_Amount             0
Gender                    0
Academic_Qualification    0
Marital                   0
Age_Years                 0
Repayment_Status_Jan      0
Repayment_Status_Feb      0
Repayment_Status_March    0
Repayment_Status_April    0
Repayment_Status_May      0
Repayment_Status_June     0
Jan_Bill_Amount           0
Feb_Bill_Amount           0
March_Bill_Amount         0
April_Bill_Amount         0
May_Bill_Amount           0
June_Bill_Amount          0
Previous_Payment_Jan      0
Previous_Payment_Feb      0
Previous_Payment_March    0
Previous_Payment_April    0
Previous_Payment_May      0
Previous_Payment_June     0
Default_Payment           0
dtype: int64

In [6]:
# Sampling 

In [7]:

from sklearn.model_selection import train_test_split

bcc_train , bcc_test = train_test_split(bcc , test_size = 0.2)

bcc_train_x = bcc_train.iloc[ : , 0:25]
bcc_train_y = bcc_train.iloc[ : , -1]

bcc_test_x = bcc_test.iloc[ : , 0:25]
bcc_test_y = bcc_test.iloc[ : , -1]

print(bcc_train_x.shape)
print(bcc_train_y.shape)

print(bcc_test_x.shape)
print(bcc_test_y.shape)

(24000, 25)
(24000,)
(6000, 25)
(6000,)


In [8]:
# Model Selection 

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
logbcc = LogisticRegression(class_weight='balanced')

In [11]:
# Fit the model

In [12]:
logbcc.fit(bcc_train_x , bcc_train_y)

C:\Users\Fahim\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(class_weight='balanced')

In [13]:
# Prediction over test data 

In [14]:
pred_bcc = logbcc.predict(bcc_test_x)
pred_bcc

array([1, 0, 1, ..., 0, 1, 1], dtype=int64)

In [15]:
# Import the sklearn.metrics to import confusion matrix

In [16]:
from sklearn.metrics import confusion_matrix

In [17]:
# Check confusion matrix

tab_bcc = confusion_matrix(pred_bcc , bcc_test_y)
tab_bcc

array([[2994,  566],
       [1688,  752]], dtype=int64)

In [18]:
# Check the accuracy

Acc_bcc = tab_bcc.diagonal().sum()  / tab_bcc.sum() * 100
Acc_bcc

62.43333333333333

In [19]:
# Sensitivity

Tpr = tab_bcc[1][1] / (tab_bcc[1][1] + tab_bcc[0][1])
Tpr

0.5705614567526556

In [20]:
# Specificity

Fpr = tab_bcc[1][0] / (tab_bcc[1][0] + tab_bcc[0][0])
Fpr

0.3605296881674498

In [21]:
# B - Beta values

logbcc.coef_

array([[ 1.54477028e-05, -1.60333601e-06,  4.40682033e-06,
         7.17753945e-06,  4.38093128e-06,  1.51052836e-04,
         2.48896411e-05,  2.10788320e-05,  1.78735344e-05,
         1.57154040e-05,  1.43355817e-05,  1.34499168e-05,
        -1.47591918e-06,  1.70631643e-07,  1.50222901e-06,
        -6.58483597e-07,  4.40361288e-06,  1.11440507e-06,
        -1.61383341e-05, -1.03666418e-05, -5.21047262e-06,
        -6.92824927e-06, -3.60803706e-06, -3.53306769e-06,
         3.64777318e-05]])

In [22]:
# Intercept or c value

logbcc.intercept_

array([3.69838621e-06])

In [23]:
# Predicted probability 

pred_prob_test = logbcc.predict_proba(bcc_test_x)
pred_prob_test

array([[0.42441089, 0.57558911],
       [0.56753296, 0.43246704],
       [0.48512864, 0.51487136],
       ...,
       [0.5083146 , 0.4916854 ],
       [0.41804085, 0.58195915],
       [0.43026704, 0.56973296]])

In [24]:
# Area Under Curve 

In [25]:
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

In [26]:
# Area Under Curve 

log_roc_buc  = roc_auc_score(pred_bcc , bcc_test_y)
log_roc_buc

0.5746039786332657

In [27]:
# Predicted probability with Data Frame representation

pred_value_prob = pd.DataFrame(pred_prob_test)
pred_value_prob

0         1
0     0.424411  0.575589
1     0.567533  0.432467
2     0.485129  0.514871
3     0.906645  0.093355
4     0.393345  0.606655
...        ...       ...
5995  0.622509  0.377491
5996  0.485378  0.514622
5997  0.508315  0.491685
5998  0.418041  0.581959
5999  0.430267  0.569733

[6000 rows x 2 columns]